Allow reading RPC parameters from env
zcash-hackworks/pyZcash pull request #1
Opened 2019-09-25 17:22 UTC by benzcash

Purpose: Disconnecting process for containerization.

Changes: This allows providing setting from the environment instead or relying on the `zcash.conf` file being available.

Falls back to original behavior if no ENV set.

2019-09-25 18:03 UTC, mdr0id requested changes
Is this assumed to always run in a none Windows environment?

See: https://github.com/zcash/zcash/blob/337e62e123c1d8d435277c76fa4a84d04a5ede1f/qa/rpc-tests/test.py#L30-L35

2019-09-25 21:09 UTC, charlieok commented
Based on the description of this repo ("python rpc interface customized for zfaucet. incomplete"), it's probably only ever been used by zfaucet, and never on windows. Also, that call to 'expanduser' was already there; it's just being moved into an 'else' block here.

2019-09-25 21:10 UTC, charlieok commented
12factor FTW
https://12factor.net/config

2019-10-09 14:34 UTC, mdr0id approved these changes
ACK

2019-10-09 14:34 UTC, merged